# Copyright 2025 NXP
#
# SPDX-License-Identifier: Apache-2.0
#
# Safety_iec60730b Zephyr west manifest
#
# Description:
#   Used for setting up freestanding safety_iec60730b module and only necessary Zephyr components.
#
# How to set up:
#   safety_iec60730b module initialization
#     1. west init -m <iec60730b_repository_URL> [--mr <iec60730b_revision_or_branch>] <folder_name>
#     2. cd <folder_name>
#     3. west update
#
# For more information, see zephyr/README.rst
#

manifest:
  self:
    path: modules/safety/iec60730b

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.3.0-rc1
      import:
        name-allowlist:
          - cmsis_6    # required by the ARM port for Cortex-M
          - hal_nxp    # required by NXP boards
